service:
    name: {{ projectName }}-messages
provider:
    name: aws
    runtime: nodejs6.10
    region: us-west-1
    memorySize: 128
    timeout: 16
package:
    exclude:
        - '*.js'
        - '*.yml'
    include:
        - handler.js
    excludeDevDependencies: false
functions:
    handleMessage:
        environment: ${file(./env.yml):${self:provider.stage}}
        handler: handler.handleMessage
        events:
            -
                http:
                    path: messages/handle
                    method: post
