service:
  name: {{ projectName }}-messages
provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  memorySize: 128
  timeout: 16
  environment: ${file(./env.yml):${self:provider.stage}}
package:
  exclude:
    - '*.js'
    - '*.yml'
  include:
    - handler.js
  excludeDevDependencies: false
functions:
  handleMessage:
    handler: handler.handleMessage
    events:
      - http:
          path: messages/handle
          method: post
